name: Post welcome comment
on:
  pull_request:
    types: [opened]
jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run local k6 test
      uses: grafana/k6-action@v0.2.0
      with:
        filename: test.js
